version: 2
jobs:
  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - run: yarn run -s format -l
  build-frontend:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: cd web; yarn; yarn build; yarn export
  build-functions:
    working_directory: ~/app
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn
      - run:
          name: Build functions
          command: cd functions; yarn; yarn build

workflows:
  version: 2
  main:
    jobs:
      - lint
      - build-frontend
      - build-functions
