version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/vendor
      - /usr/src/app/log
      - /usr/src/app/.git
      - /usr/src/app/app/controllers
      - /usr/src/app/app/models
      - /usr/src/app/app/views
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - RAILS_ENV=development
      - TWITTER_CK=${TWITTER_CK}
      - TWITTER_CS=${TWITTER_CS}
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - SECURITY_SALT=ea703e7aa1efda0064eaa507d9e8ab7e
      - ADMIN_TOKEN=1
      - TZ=${TZ}
    depends_on:
      - db
      - redis
  rails:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/vendor
      - /usr/src/app/log
      - /usr/src/app/.git
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - RAILS_ENV=development
      - TWITTER_CK=${TWITTER_CK}
      - TWITTER_CS=${TWITTER_CS}
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - SECURITY_SALT=ea703e7aa1efda0064eaa507d9e8ab7e
      - ADMIN_TOKEN=1
      - TZ=${TZ}
    depends_on:
      - db
      - redis
  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/vendor
  #     - /usr/src/app/log
  #     - /usr/src/app/.git
  #   environment:
  #     - RAILS_ENV=development
  #     - TWITTER_CK=${TWITTER_CK}
  #     - TWITTER_CS=${TWITTER_CS}
  #     - ROOT_DOMAIN=${ROOT_DOMAIN}
  #     - SECURITY_SALT=ea703e7aa1efda0064eaa507d9e8ab7e
  #     - ADMIN_TOKEN=1
  #     - TZ=${TZ}
  #   depends_on:
  #     - db
  #     - redis
